[package]
name = "agate"
version = "1.2.1"
authors = ["Matt Brubeck <mbrubeck@limpet.net>"]
description = "Very simple server for the Gemini hypertext protocol"
keywords = ["server", "gemini", "hypertext", "internet", "protocol"]
categories = ["network-programming"]
repository = "https://github.com/mbrubeck/agate"
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
async-tls = { version = "0.9.0", default-features = false, features = ["server"] }
async-std = "1.5"
mime_guess = "2.0"
once_cell = "1.4"
rustls = "0.18.0"
url = "2.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
